* pywik
Welcome to pywik the static webserver csv logfile analyzer.
** Setup
   install the dependencies:
   #+BEGIN_SRC
   virtualenv --no-site-packages env
   source env/bin/activate
   pip install -r deps.txt
   #+END_SRC
   setup environment for pywik:
   #+BEGIN_SRC
   mkdir logs
   ./updatelists.sh
   mkdir data/myhost
   touch data/myhost/goodpaths
   touch data/myhost/ignoremissing
   touch data/myhost/ignorepaths
   touch data/myhost/ownhosts
   #+END_SRC
** Host specific files
   pywik uses a few host specific files, which improve the output massively.
*** ownhosts
    a list of hostnames that are considered part of your
    infrastructure. Any log entries with referers from other than
    these hosts are considered external hits.
*** goodpath
    Any path considered a page visit, each line is a regexp.
*** ignoremissing
    Any path that is regularly generating 404 responses, each line is a regexp.
*** ignorepaths
    Any path that is uninteresting for tracking pageviews, like all
    requisites for pages (e.g. .css, .js, etc files), each line is a
    regexp.
** Web-server logformat
   set your webserver (nginx) to use these as logformats:
   #+BEGIN_SRC
   log_format csv-http  '"$time_local";$connection;"$remote_addr";0;"$http_host";"$request";'
      '$status;$request_length;$body_bytes_sent;$request_time;"$http_referer";"$remote_user";'
      '"$http_user_agent";"$http_x_forwarded_for";$msec';
   log_format csv-https '"$time_local";$connection;"$remote_addr";1;"$http_host";"$request";'
      '$status;$request_length;$body_bytes_sent;$request_time;"$http_referer";"$remote_user";'
      '"$http_user_agent";"$http_x_forwarded_for";$msec';
   #+END_SRC
   and for your hosts use them for logging:
   #+BEGIN_SRC
    access_log /var/log/nginx/access.csv csv-http;
   #+END_SRC
   or
   #+BEGIN_SRC
    access_log /var/log/nginx/access.csv csv-https;
   #+END_SRC
   respectively for https hosts stanzas.
** Running pywik
   #+BEGIN_SRC
   ./fetchlogs.sh myhost.net
   ./pywik.py month myhost <logs/access.csv | less
   #+END_SRC
   if you find anything interesting, you can extract all logentries
   matching certain fields:
   #+BEGIN_SRC
   ./getentries.py logs/access.csv myhost path 'cart.php?a=asdf&templatefile=../../../configuration.php'
   #+END_SRC
** Bugs
   pywik is slow, due to resolving hostnames on each run, if you want to
   speed it up, use a dnscache.
